baseURL = "https://example.com/"
title = "Subre Theme"
# copyright = "John Doe; all rights reserved."
defaultContentLanguage = "en"
languageCode = "en-US"
theme = ["gohugo-theme-subre"]

paginate = 3

[author]
name = "John Doe"
suffix = "Dummy"
email = "john.doe@example.com"
phone = "+1 202-918-2132"
address = "3423 S 160th St, 98188 SeaTac"
bio = "John Doe's bio."

[params]
subtitle = "Demo"
description = "My wonderful site description"
keywords = ["tailwind", "mobile", "light"]
footerMention = "Some mention on footer section"

# https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
# themeColor = "#FFF"
# themeColorLight = "#FFF"
# themeColorDark = "#000"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true


[languages]
  [languages.fr]
    languageCode = "fr-FR"
    weight = 1
  [languages.en]
    languageCode = "en-US"
     [languages.en.params]
    weight = 2